from array import *
arr = array('i', [10, 20, 30, 40, 50])
arr.append(60)
arr.extend([70, 80])
print("After Adding new elements:", arr)
arr.insert(3, 99)
print("After inserting:", arr) 
arr.remove(20)
print("After removing:", arr)
n = arr.pop()
print("After pop operation:", arr)
print("Popped element:", n)
indx = arr.index(30)
print("Index for Element 30:", indx)
lst = arr.tolist()
print('List:', lst)
