str = 'Core Python'
print(str[0:9:1])
print(str[0:9:2])
print(str[::])
print(str[2:4:1])
print(str[2::])
print(str[:4:])
print(str[-4:-1])
print(str[-6::])
print(str[-1:-4:-1])
print(str[-1::-1])
print(str*2)
print(str[5:7]*3)
